//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountToItem
    {
        public int DiscItemId { get; set; }
        public int StorehouseItemId { get; set; }
        public int DiscountId { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual StorehouseItem StorehouseItem { get; set; }
    }
}
