//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace ElectronicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.CategoryItems = new HashSet<CategoryItem>();
            this.Consignments = new HashSet<Consignment>();
        }

        [DisplayName("Модель")]
        public string Model { get; set; }

        public int ProducerId { get; set; }

        public int ItemId { get; set; }

        [DisplayName("Колір")]
        public string Color { get; set; }

        [DisplayName("Матеріал")]
        public string Material { get; set; }

        [DisplayName("Додаткова інформація")]
        public string Description { get; set; }
        
        [DisplayName("Дата релізу")]
        public Nullable<int> ReleaseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryItem> CategoryItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consignment> Consignments { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
